// presets.js — built-in setups for the Backing Track page (BandPresets): a tune together with every
// band setting, in the format the page's "Save and load" section writes.
// To add one: on the page, save a setup, press "Show JSON for the defaults", and paste the object into
// this list (then bump this file's ?v= in tools/_backing-track.qmd). They appear in the Changes menu
// under "Built-in setups".
(function (global) {
  // The three tunes below carry a figure every player should know: the line or rhythm is a catalog
  // entry (bass / comp ids sowhat, killerjoe, songfather), so it can be chosen on any other tune too.
  global.BandPresets = [
    {"v": 1, "name": "So What (bass call and answer on the head)", "abc": "X:1\nT:So What changes\nM:4/4\nL:1/4\nK:Dm\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Ebm7\"z4 | \"Ebm7\"z4 | \"Ebm7\"z4 | \"Ebm7\"z4 |\n\"Ebm7\"z4 | \"Ebm7\"z4 | \"Ebm7\"z4 | \"Ebm7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |]", "tempo": 136, "style": "swing", "unlock": false, "feel": "swing", "bass": "sowhat", "groove": "auto", "rhythm": "sowhat", "voicing": "sowhat", "fields": {"bt-comp": "piano", "bt-figs": "head", "bt-ext": "0", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Killer Joe (two-bar vamp)", "abc": "X:1\nT:Killer Joe changes\nM:4/4\nL:1/4\nK:C\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |\n\"Em7b5\"z4 | \"A7b9\"z4 | \"Ebm7\"z4 | \"Ab7\"z4 |\n\"A7\"z4 | \"Ab7\"z4 | \"Em7\"z4 | \"A7\"z4 |\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |\n\"C7\"z4 | \"Bb7\"z4 | \"C7\"z4 | \"Bb7\"z4 |]", "tempo": 120, "style": "swing", "unlock": false, "feel": "swing", "bass": "killerjoe", "groove": "auto", "rhythm": "charleston", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0.35", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Song for My Father (bass figure, four-bar intro)", "abc": "X:1\nT:Song for My Father changes\nM:4/4\nL:1/4\nK:Fm\n\"Fm9\"z4 | \"Fm9\"z4 | \"Eb9\"z4 | \"Eb9\"z4 |\n\"Db9\"z4 | \"C7\"z4 | \"Fm9\"z4 | \"Fm9\"z4 |\n\"Fm9\"z4 | \"Fm9\"z4 | \"Eb9\"z4 | \"Eb9\"z4 |\n\"Db9\"z4 | \"C7\"z4 | \"Fm9\"z4 | \"Fm9\"z4 |\n\"Eb9\"z4 | \"Eb9\"z4 | \"Fm9\"z4 | \"Fm9\"z4 |\n\"Eb9\"z4 | \"Db9\"z2 \"C7\"z2 | \"Fm9\"z4 | \"Fm9\"z4 |]", "tempo": 132, "style": "bossa", "unlock": false, "feel": "straight", "bass": "songfather", "groove": "bossa", "rhythm": "bossa", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0.35", "bt-variation": "0.6", "bt-intro": "vamp", "bt-intro-bars": "4"}, "checks": {"bt-intro-nodrums": true}},
    {"v": 1, "name": "Footprints (waltz ostinato)", "abc": "X:1\nT:Footprints changes\nM:3/4\nL:1/4\nK:Cm\n\"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 |\n\"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 |\n\"Fm7\"z3 | \"Fm7\"z3 | \"Fm7\"z3 | \"Fm7\"z3 |\n\"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 |\n\"F#m7b5\"z3 | \"F7#11\"z3 | \"E7#9\"z3 | \"A7#9\"z3 |\n\"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 | \"Cm7\"z3 |]", "tempo": 168, "style": "swing", "unlock": false, "feel": "swing", "bass": "footprints", "groove": "auto", "rhythm": "auto", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0.35", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "All Blues (6/8 vamp)", "abc": "X:1\nT:All Blues changes\nM:6/8\nL:1/8\nK:G\n\"G7\"z6 | \"G7\"z6 | \"G7\"z6 | \"G7\"z6 |\n\"G7\"z6 | \"G7\"z6 | \"G7\"z6 | \"G7\"z6 |\n\"C7\"z6 | \"C7\"z6 | \"C7\"z6 | \"C7\"z6 |\n\"G7\"z6 | \"G7\"z6 | \"G7\"z6 | \"G7\"z6 |\n\"D7#9\"z6 | \"D7#9\"z6 | \"Eb7#9\"z6 | \"D7#9\"z6 |\n\"G7\"z6 | \"G7\"z6 | \"G7\"z6 | \"G7\"z6 |]", "tempo": 69, "style": "swing", "unlock": false, "feel": "swing", "bass": "allblues", "groove": "auto", "rhythm": "pad", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0.35", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Maiden Voyage (the comping rhythm)", "abc": "X:1\nT:Maiden Voyage changes\nM:4/4\nL:1/4\nK:D\n\"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 |\n\"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 |\n\"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 |\n\"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 |\n\"Eb7sus\"z4 | \"Eb7sus\"z4 | \"Eb7sus\"z4 | \"Eb7sus\"z4 |\n\"C#m7\"z4 | \"C#m7\"z4 | \"C#m7\"z4 | \"C#m7\"z4 |\n\"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 | \"D7sus\"z4 |\n\"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 | \"F7sus\"z4 |]", "tempo": 120, "style": "boogaloo", "unlock": false, "feel": "straight", "bass": "maiden", "groove": "auto", "rhythm": "maiden", "voicing": "sowhat", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Take Five (5/4 vamp)", "abc": "X:1\nT:Take Five changes\nM:5/4\nL:1/4\nK:Ebm\n\"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 |\n\"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 |\n\"Cbmaj7\"z3 \"Abm6\"z2 | \"Bbm7\"z3 \"Ebm7\"z2 | \"Abm7\"z3 \"Db7\"z2 | \"Gbmaj7\"z5 |\n\"Cbmaj7\"z3 \"Abm6\"z2 | \"Bbm7\"z3 \"Ebm7\"z2 | \"Abm7\"z3 \"Db7\"z2 | \"Fm7\"z3 \"Bb7\"z2 |\n\"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 |\n\"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 | \"Ebm\"z3 \"Bbm7\"z2 |]", "tempo": 168, "style": "swing", "unlock": false, "feel": "swing", "bass": "takefive", "groove": "auto", "rhythm": "takefive", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Chameleon (two-bar vamp)", "abc": "X:1\nT:Chameleon changes\nM:4/4\nL:1/4\nK:Bbm\n\"Bbm7\"z4 | \"Eb7\"z4 | \"Bbm7\"z4 | \"Eb7\"z4 |\n\"Bbm7\"z4 | \"Eb7\"z4 | \"Bbm7\"z4 | \"Eb7\"z4 |]", "tempo": 96, "style": "boogaloo", "unlock": false, "feel": "straight", "bass": "chameleon", "groove": "funk", "rhythm": "stabs", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0", "bt-variation": "0.6", "bt-bass-sound": "electric"}, "checks": {}},
    {"v": 1, "name": "Cantaloupe Island (16 bars)", "abc": "X:1\nT:Cantaloupe Island changes\nM:4/4\nL:1/4\nK:Fm\n\"Fm7\"z4 | \"Fm7\"z4 | \"Fm7\"z4 | \"Fm7\"z4 |\n\"Db7\"z4 | \"Db7\"z4 | \"Db7\"z4 | \"Db7\"z4 |\n\"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 | \"Dm7\"z4 |\n\"Fm7\"z4 | \"Fm7\"z4 | \"Fm7\"z4 | \"Fm7\"z4 |]", "tempo": 112, "style": "boogaloo", "unlock": false, "feel": "straight", "bass": "riff", "groove": "auto", "rhythm": "stabs", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0", "bt-variation": "0.6"}, "checks": {}},
    {"v": 1, "name": "Blue Bossa (16 bars)", "abc": "X:1\nT:Blue Bossa changes\nM:4/4\nL:1/4\nK:Cm\n\"Cm7\"z4 | \"Cm7\"z4 | \"Fm7\"z4 | \"Fm7\"z4 |\n\"Dm7b5\"z4 | \"G7\"z4 | \"Cm7\"z4 | \"Cm7\"z4 |\n\"Ebm7\"z4 | \"Ab7\"z4 | \"Dbmaj7\"z4 | \"Dbmaj7\"z4 |\n\"Dm7b5\"z4 | \"G7\"z4 | \"Cm7\"z4 | \"Dm7b5\"z2 \"G7\"z2 |]", "tempo": 132, "style": "bossa", "unlock": false, "feel": "straight", "bass": "bossa", "groove": "bossa", "rhythm": "bossa", "voicing": "rootless", "fields": {"bt-comp": "piano", "bt-figs": "always", "bt-ext": "0.35", "bt-variation": "0.6"}, "checks": {}}
  ];
})(typeof window !== "undefined" ? window : globalThis);
