// apps/lsa/instructions.js
// Per-criterion instruction text -- the "Students ..." line transcribed verbatim
// from each source book (the line just above the E/M/D staves). Every criterion page
// actually has TWO instruction blocks: a top preamble ("Sing tonal sequence... Sing
// class patterns...", teacher-led whole-class warm-up) and, right above the staves, the
// teacher/student pair for the individual pattern itself ("Teacher sings pattern...
// Students sing only first pitch..."). Only the "Students..." half of that second block
// belongs here. Tonal Book 1 (t1-) was re-transcribed directly from `JRI Tonal Register
// LSAs Book 1 FULL 2015_04_20_15_03_06.pdf` (pages 3-96, one criterion per page) after
// an earlier pass over JRI Tonal Register Analysis.docx had mistakenly captured the top
// preamble instead. Tonal Book 2 (t2-) and both Rhythm books (r1-, r2-) were read
// directly off the rendered PDF pages and spot-verified against the same "Students..."
// line -- fast pass, same caveats as the pattern data itself, see the comments above the
// t2-/r1-/r2- entries in pattern-object.js / rhythm-pattern-object.js.
const LSA_INSTRUCTIONS = {
  "r1-1A1": "Students chant patterns using \"bah.\"",
  "r1-1B1": "Students chant patterns using \"bah.\"",
  "r1-2A1": "Students name the meter and functions of the patterns.",
  "r1-2A2": "Students name the meter and functions of the patterns.",
  "r1-2B1": "Students chant patterns using rhythm syllables.",
  "r1-2C1": "Students chant patterns using rhythm syllables.",
  "r1-3A1": "Students chant patterns using \"bah.\"",
  "r1-3A2": "Students chant patterns using \"bah.\"",
  "r1-3B1": "Students chant patterns using \"bah.\"",
  "r1-3B2": "Students chant patterns using \"bah.\"",
  "r1-4A1": "Students name the meter and the functions of the patterns.",
  "r1-4A2": "Students name the meter and the functions of the patterns.",
  "r1-4B1": "Students chant patterns using rhythm syllables.",
  "r1-4B2": "Students chant patterns using rhythm syllables.",
  "r1-4C1": "Students chant patterns using rhythm syllables.",
  "r1-4C2": "Students chant patterns using rhythm syllables.",
  "r1-5A1": "Students name the meter and the functions of the patterns.",
  "r1-5A2": "Students chant patterns using rhythm syllables.",
  "r1-5A3": "Students chant patterns using rhythm syllables.",
  "r1-5B1": "Students name the meter and the functions of the patterns.",
  "r1-5B2": "Students chant patterns using rhythm syllables.",
  "r1-5B3": "Students chant patterns using rhythm syllables.",
  "r1-6A1": "Students name the meter of each series.",
  "r1-6A2": "Students name the meter of each series.",
  "r1-7A1": "Students chant any other patterns in usual duple in creative response using rhythm syllables.",
  "r1-7A2": "Students chant any other patterns in usual triple in creative response using rhythm syllables.",
  "r1-7B1": "Students chant any other macro and micro beat and/or division and elongation patterns in usual duple four macro beats long in improvisatory response using rhythm syllables.",
  "r1-7B2": "Students chant any other macro and micro beat and/or division and elongation patterns in usual triple four macro beats long in improvisatory response using rhythm syllables.",
  "r1-8A1": "Students chant patterns using \"bah.\"",
  "r1-8A2": "Students chant patterns using \"bah.\"",
  "r1-8A3": "Students chant patterns using \"bah.\"",
  "r1-8B1": "Students chant patterns using \"bah.\"",
  "r1-8B2": "Students chant patterns using \"bah.\"",
  "r1-8B3": "Students chant patterns using \"bah.\"",
  "r1-9A1": "Students name the meter and the functions of the patterns.",
  "r1-9A2": "Students name the meter and the functions of the patterns.",
  "r1-9B1": "Students chant patterns using rhythm syllables.",
  "r1-9B2": "Students chant patterns using rhythm syllables.",
  "r1-9B3": "Students chant patterns using rhythm syllables.",
  "r1-9C1": "Students chant patterns using rhythm syllables.",
  "r1-9C2": "Students chant patterns using rhythm syllables.",
  "r1-9C3": "Students chant patterns using rhythm syllables.",
  "r1-10A1": "Students read patterns using rhythm syllables.",
  "r1-10A2": "Students read patterns using rhythm syllables.",
  "r1-10A3": "Students read patterns using rhythm syllables.",
  "r1-10B1": "Students read patterns using rhythm syllables.",
  "r1-10B2": "Students read patterns using rhythm syllables.",
  "r1-10B3": "Students read patterns using rhythm syllables.",
  "r1-11A1": "Students chant patterns using \"bah.\"",
  "r1-11A2": "Students chant patterns using \"bah.\"",
  "r1-11A3": "Students chant patterns using \"bah.\"",
  "r1-11B1": "Students chant patterns using \"bah.\"",
  "r1-11B2": "Students chant patterns using \"bah.\"",
  "r1-11B3": "Students chant patterns using \"bah.\"",
  "r1-12A1": "Students name the meter and the functions of the patterns.",
  "r1-12A2": "Students name the meter and the functions of the patterns.",
  "r1-12B1": "Students chant patterns using rhythm syllables.",
  "r1-12B2": "Students chant patterns using rhythm syllables.",
  "r1-12B3": "Students chant patterns using rhythm syllables.",
  "r1-12C1": "Students chant patterns using rhythm syllables.",
  "r1-12C2": "Students chant patterns using rhythm syllables.",
  "r1-12C3": "Students chant patterns using rhythm syllables.",
  "r1-13A1": "Students write patterns.",
  "r1-13A2": "Students write patterns.",
  "r1-13A3": "Students write patterns.",
  "r1-13B1": "Students write patterns.",
  "r1-13B2": "Students write patterns.",
  "r1-13B3": "Students write patterns.",
  "r1-14A1": "Students read patterns using \"bah.\"",
  "r1-14A2": "Students write patterns.",
  "r1-14B1": "Students read patterns using \"bah.\"",
  "r1-14B2": "Students write patterns.",
  "r1-15A1": "Students name the meter of each series.",
  "r1-15A2": "Students name the meter of each series.",
  "r1-16A1": "Students chant patterns using \"bah.\"",
  "r1-16A2": "Students chant patterns using \"bah.\"",
  "r1-17A1": "Students name the meter and the functions of the patterns.",
  "r1-17A2": "Students chant patterns using rhythm syllables.",
  "r1-17A3": "Students chant patterns using rhythm syllables.",
  "r1-18A1": "Students chant any other patterns in usual combined in creative response using rhythm syllables.",
  "r1-18A2": "Students chant any other macro and micro beat and/or division and elongation patterns in usual combined four macro beats long in improvisatory response using rhythm syllables.",
  "r1-19A1": "Students read the patterns using rhythm syllables.",
  "r1-19A2": "Students read the patterns using rhythm syllables.",
  "r1-19B1": "Students read the patterns using rhythm syllables.",
  "r1-19B2": "Students read the patterns using rhythm syllables.",
  "r2-20A1": "Students chant patterns using \"bah.\"",
  "r2-20A2": "Students chant patterns using \"bah.\"",
  "r2-20B1": "Students chant patterns using \"bah.\"",
  "r2-20B2": "Students chant patterns using \"bah.\"",
  "r2-21A1": "Students write patterns.",
  "r2-21A2": "Students write patterns.",
  "r2-21B1": "Students write patterns.",
  "r2-21B2": "Students write patterns.",
  "r2-22A1": "Students name the meter and the functions of the patterns.",
  "r2-22A2": "Students name the meter and the functions of the patterns.",
  "r2-22B1": "Students chant patterns using rhythm syllables.",
  "r2-22B2": "Students chant patterns using rhythm syllables.",
  "r2-22C1": "Students chant patterns using rhythm syllables.",
  "r2-22C2": "Students chant patterns using rhythm syllables.",
  "r2-23A1": "Students read patterns using rhythm syllables.",
  "r2-23A2": "Students read patterns using rhythm syllables.",
  "r2-23A3": "Students read patterns using rhythm syllables.",
  "r2-23B1": "Students read patterns using rhythm syllables.",
  "r2-23B2": "Students read patterns using rhythm syllables.",
  "r2-23B3": "Students read patterns using rhythm syllables.",
  "r2-24A1": "Students chant any other patterns in usual duple in creative response using rhythm syllables.",
  "r2-24A2": "Students chant any other patterns in usual triple in creative response using rhythm syllables.",
  "r2-24B1": "Students chant any other patterns of any function in usual duple four macro beats long in improvisatory response using rhythm syllables.",
  "r2-24B2": "Students chant any other patterns of any function in usual triple four macro beats long in improvisatory response using rhythm syllables.",
  "r2-25A1": "Students chant patterns using \"bah.\"",
  "r2-25A2": "Students chant patterns using \"bah.\"",
  "r2-26A1": "Students chant patterns using \"bah.\"",
  "r2-26A2": "Students chant patterns using \"bah.\"",
  "r2-27A1": "Students name the meter and the functions of the patterns.",
  "r2-27A2": "Students chant the patterns using rhythm syllables.",
  "r2-27A3": "Students chant the patterns using rhythm syllables.",
  "r2-28A1": "Students name the meter of each series.",
  "r2-28A2": "Students name the meter of each series.",
  "r2-29A1": "Students name the meter and the functions of the patterns.",
  "r2-29A2": "Students chant patterns using rhythm syllables.",
  "r2-29B1": "Students name the meter and the functions of the patterns.",
  "r2-29B2": "Students chant patterns using rhythm syllables.",
  "r2-30A1": "Students name the meter of each series.",
  "r2-30A2": "Students name the meter of each series.",
  "r2-31A1": "Students write patterns.",
  "r2-31A2": "Students write patterns.",
  "r2-31A3": "Students write patterns.",
  "r2-31B1": "Students write patterns.",
  "r2-31B2": "Students write patterns.",
  "r2-31B3": "Students write patterns.",
  "r2-32A1": "Students read patterns using rhythm syllables.",
  "r2-32A2": "Students read patterns using rhythm syllables.",
  "r2-33A1": "Students write patterns.",
  "r2-33A2": "Students write patterns.",
  "r2-34A1": "Students chant any other patterns in usual combined in creative response using rhythm syllables.",
  "r2-34A2": "Students chant any other patterns of any function in usual combined four macro beats long in improvisation response using rhythm syllables.",
  "r2-35A1": "Students read patterns using rhythm syllables.",
  "r2-35A2": "Students read patterns using rhythm syllables.",
  "r2-35B1": "Students read patterns using rhythm syllables.",
  "r2-35B2": "Students read patterns using rhythm syllables.",
  "r2-36A1": "Students read patterns using rhythm syllables.",
  "r2-36A2": "Students read patterns using rhythm syllables.",
  "r2-36B1": "Students read patterns using rhythm syllables.",
  "r2-36B2": "Students read patterns using rhythm syllables.",
  "r2-37A1": "Students write patterns.",
  "r2-37A2": "Students write patterns.",
  "r2-37B1": "Students write patterns.",
  "r2-37B2": "Students write patterns.",
  "r2-38A1": "Students write patterns.",
  "r2-38A2": "Students write patterns.",
  "r2-38B1": "Students write patterns.",
  "r2-38B2": "Students write patterns.",
  "r2-39A1": "Students name the meters and the functions of the patterns.",
  "r2-39B1": "Students chant patterns using rhythm syllables.",
  "r2-39B2": "Students chant patterns using rhythm syllables.",
  "r2-40A1": "Students name the meter and the functions of the patterns.",
  "r2-40A2": "Students chant rhythm patterns using rhythm syllables.",
  "r2-41A1": "Students chant any other multimetric patterns in improvisation response using rhythm syllables.",
  "r2-41A2": "Students chant any other multimetric patterns in improvisation response using rhythm syllables.",
  "r2-42A1": "Students read patterns using \"bah.\"",
  "r2-42A2": "Students write patterns.",
  "r2-42B1": "Students read patterns using \"bah.\"",
  "r2-42B2": "Students write patterns.",
  "t1-1A1": "Students sing only first pitch using \"bum.\"",
  "t1-1A2": "Students sing only resting tone using \"bum.\"",
  "t1-1A3": "Students sing pattern using \"bum.\"",
  "t1-1B1": "Students sing only first pitch using \"bum.\"",
  "t1-1B2": "Students sing only resting tone using \"bum.\"",
  "t1-1B3": "Students sing pattern using \"bum.\"",
  "t1-2A1": "Students name the tonality and functions of the patterns.",
  "t1-2A2": "Students name the tonality and functions of the patterns.",
  "t1-2B1": "Students sing only first pitch using tonal syllables.",
  "t1-2B2": "Students sing only resting tone using \"Do.\"",
  "t1-2B3": "Students sing pattern using tonal syllables.",
  "t1-2C1": "Students sing only first pitch using tonal syllables.",
  "t1-2C2": "Students sing only resting tone using \"La.\"",
  "t1-2C3": "Students sing pattern using tonal syllables.",
  "t1-3A1": "Students sing any other pattern in major in creative response using tonal syllables.",
  "t1-3A2": "Students sing any other pattern in minor in creative response using tonal syllables.",
  "t1-3B1": "Students sing any other tonic and/or dominant pattern in major in improvisatory response using tonal syllables.",
  "t1-3B2": "Students sing any other tonic and/or dominant pattern in minor in improvisatory response using tonal syllables.",
  "t1-4A1": "Students sing pattern using \"bum.\"",
  "t1-4A2": "Students sing pattern using \"bum.\"",
  "t1-4B1": "Students sing pattern using \"bum.\"",
  "t1-4B2": "Students sing pattern using \"bum.\"",
  "t1-5A1": "Students name the tonality and functions of the pattern.",
  "t1-5A2": "Students name the tonality and functions of the pattern.",
  "t1-5B1": "Students sing patterns using tonal syllables.",
  "t1-5B2": "Students sing patterns using tonal syllables.",
  "t1-5C1": "Students sing patterns using tonal syllables.",
  "t1-5C2": "Students sing patterns using tonal syllables.",
  "t1-7A1": "Students sing patterns using \"bum.\"",
  "t1-7A2": "Students sing patterns using \"bum.\"",
  "t1-7B1": "Students sing patterns using \"bum.\"",
  "t1-7B2": "Students sing patterns using \"bum.\"",
  "t1-8A1": "Students sing patterns using tonal syllables.",
  "t1-8A2": "Students sing patterns using tonal syllables.",
  "t1-8B1": "Students sing patterns using tonal syllables.",
  "t1-8B2": "Students sing patterns using tonal syllables.",
  "t1-9A1": "Students name the tonality and the functions of the patterns.",
  "t1-9A2": "Students sing patterns using tonal syllables.",
  "t1-9A3": "Students sing patterns using tonal syllables.",
  "t1-9B1": "Students name the tonality and the functions of the patterns.",
  "t1-9B2": "Students sing patterns using tonal syllables.",
  "t1-9B3": "Students sing patterns using tonal syllables.",
  "t1-10A1": "Students sing patterns using \"bum.\"",
  "t1-10A2": "Students sing patterns using \"bum.\"",
  "t1-18A3": "Students write patterns.",
  "t2-22A1": "Students name the tonality and the functions of the patterns.",
  "t2-22A2": "Students sing patterns using tonal syllables.",
  "t2-22A3": "Students sing patterns using tonal syllables.",
  "t2-22B1": "Students name the tonality and the functions of the patterns.",
  "t2-22B2": "Students sing patterns using tonal syllables.",
  "t2-22B3": "Students sing patterns using tonal syllables.",
  "t2-23A1": "Students write patterns.",
  "t2-23A2": "Students write patterns.",
  "t2-23B1": "Students write patterns.",
  "t2-23B2": "Students write patterns.",
  "t2-24A1": "Students sing any other patterns in mixolydian in creative response using tonal syllables.",
  "t2-24A2": "Students sing any other patterns in dorian in creative response using tonal syllables.",
  "t2-24B1": "Students sing any other tonic, subtonic and/or subdominant patterns in mixolydian in improvisatory response using tonal syllables. (approx, header text partly cut off in source, reconstructed from B2's parallel wording)",
  "t2-24B2": "Students sing any other tonic, subtonic and/or subdominant patterns in dorian in improvisatory response using tonal syllables.",
  "t2-25A1": "Students sing patterns using \"bum.\"",
  "t2-25A2": "Students sing patterns using \"bum.\"",
  "t2-25B1": "Students sing patterns using \"bum.\"",
  "t2-25B2": "Students sing patterns using \"bum.\"",
  "t2-26A1": "Students write patterns.",
  "t2-26A2": "Students write patterns.",
  "t2-26B1": "Students write patterns.",
  "t2-26B2": "Students write patterns.",
  "t2-27A1": "Students sing patterns using \"bum.\"",
  "t2-27A2": "Students sing patterns using \"bum.\"",
  "t2-27B1": "Students sing patterns using \"bum.\"",
  "t2-27B2": "Students sing patterns using \"bum.\"",
  "t2-28A1": "Students name the tonality and functions of the patterns.",
  "t2-28A2": "Students name the tonality and functions of the patterns.",
  "t2-28B1": "Students sing patterns using tonal syllables.",
  "t2-28B2": "Students sing patterns using tonal syllables.",
  "t2-28C1": "Students sing patterns using tonal syllables.",
  "t2-28C2": "Students sing patterns using tonal syllables.",
  "t2-29A1": "Students sing any other patterns in major in creative response using tonal syllables.",
  "t2-29A2": "Students sing any other patterns in minor in creative response using tonal syllables.",
  "t2-29B1": "Students sing any other patterns of any function in major in improvisatory response using tonal syllables.",
  "t2-29B2": "Students sing any other patterns of any function in minor in improvisatory response using tonal syllables.",
  "t2-30A1": "Students indicate whether the series of patterns is multitonal, multikeyal, or both.",
  "t2-30A2": "Students indicate whether the series of patterns is multitonal, multikeyal, or both.",
  "t2-30B1": "Students sing patterns using tonal syllables.",
  "t2-30B2": "Students sing patterns using tonal syllables.",
  "t2-30C1": "Students sing patterns using tonal syllables.",
  "t2-30C2": "Students sing patterns using tonal syllables.",
  "t2-31A1": "Students indicate why the series of patterns is both multitonal and multikeyal.",
  "t2-31A2": "Students indicate why the series of patterns is both multitonal and multikeyal.",
  "t2-31B1": "Students indicate why the series of patterns is both multitonal and multikeyal.",
  "t2-31B2": "Students indicate why the series of patterns is both multitonal and multikeyal.",
  "t2-32A1": "Students sing patterns using \"bum.\"",
  "t2-32A2": "Students sing patterns using \"bum.\"",
  "t2-32B1": "Students sing patterns using \"bum.\"",
  "t2-32B2": "Students sing patterns using \"bum.\"",
  "t2-33A1": "Students name the tonality and the functions of the patterns.",
  "t2-33A2": "Students name the tonality and the functions of the patterns.",
  "t2-33B1": "Students sing patterns using tonal syllables.",
  "t2-33B2": "Students sing patterns using tonal syllables.",
  "t2-33C1": "Students sing patterns using tonal syllables.",
  "t2-33C2": "Students sing patterns using tonal syllables.",
  "t2-34A1": "Students name the tonality of each series.",
  "t2-34A2": "Students name the tonality of each series.",
  "t2-35A1": "Students read patterns using tonal syllables.",
  "t2-35A2": "Students read patterns using tonal syllables.",
  "t2-35B1": "Students read patterns using tonal syllables.",
  "t2-35B2": "Students read patterns using tonal syllables.",
  "t2-36A1": "Students name the tonality and the functions of the patterns.",
  "t2-36A2": "Students sing patterns using tonal syllables.",
  "t2-36A3": "Students sing patterns using tonal syllables.",
  "t2-36B1": "Students name the tonality and the functions of the patterns.",
  "t2-36B2": "Students sing patterns using tonal syllables.",
  "t2-36B3": "Students sing patterns using tonal syllables.",
  "t2-37A1": "Students write patterns.",
  "t2-37A2": "Students write patterns.",
  "t2-37B1": "Students write patterns.",
  "t2-37B2": "Students write patterns.",
  "t2-38A1": "Students read patterns using tonal syllables.",
  "t2-38A2": "Students read patterns using tonal syllables.",
  "t2-38B1": "Students read patterns using tonal syllables.",
  "t2-38B2": "Students read patterns using tonal syllables.",
  "t2-39A1": "Students read patterns using \"bum.\"",
  "t2-39A2": "Students write patterns.",
  "t2-39B1": "Students read patterns using \"bum.\"",
  "t2-39B2": "Students write patterns.",
  "t2-40A1": "Students indicate which series of patterns are multitonal, multikeyal, or both.",
  "t2-40A2": "Students indicate which series of patterns are multitonal, multikeyal, or both.",
  "t2-40B1": "Students indicate which series of patterns are multitonal, multikeyal, or both.",
  "t2-40B2": "Students indicate which series of patterns are multitonal, multikeyal, or both.",
  "t2-41A1": "Students write patterns.",
  "t2-41A2": "Students write patterns.",
  "t2-41B1": "Students write patterns.",
  "t2-41B2": "Students write patterns.",
  "t2-42A1": "Students sing an improvisation multikeyal response using tonal syllables.",
  "t2-42A2": "Students sing an improvisation multikeyal response using tonal syllables.",
  "t2-42B1": "Students sing an improvisation multitonal response using tonal syllables.",
  "t2-42B2": "Students sing an improvisation multikeyal and multitonal response using tonal syllables.",
};
