const fs = require("fs"), vm = require("vm");
vm.runInThisContext(fs.readFileSync("/Users/sean.coleman/Projects/everything-music-site/apps/shared/voicings.js", "utf8"));
const N = ["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"];
const nn = m => N[m % 12] + (Math.floor(m / 12) - 1);
const show = (title, list) => { console.log("\n== " + title + " (" + list.length + ")"); list.forEach(c => console.log("  " + c.label.padEnd(44) + c.midis.map(nn).join(" ").padEnd(22) + (c.strings ? c.strings.map(s => s.string + ":" + s.fret).join(" ") : ""))); };
const C7 = { root:0, intervals:[0,4,7,10] }, Cmaj7 = { root:0, intervals:[0,4,7,11] }, C = { root:0, intervals:[0,4,7] };
show("piano drop2 Cmaj7", ChordVoicings.piano(Cmaj7, "drop2"));
show("piano drop3 Cmaj7", ChordVoicings.piano(Cmaj7, "drop3"));
show("piano drop2 C", ChordVoicings.piano(C, "drop2"));
show("piano drop3 C", ChordVoicings.piano(C, "drop3"));
show("piano drop2 C13", ChordVoicings.piano({ root:0, intervals:[0,4,7,10,14,21] }, "drop2"));
show("piano drop2 C9", ChordVoicings.piano({ root:0, intervals:[0,4,7,10,14] }, "drop2"));
show("piano drop2 C5", ChordVoicings.piano({ root:0, intervals:[0,7] }, "drop2"));
show("guitar drop2 C7", ChordVoicings.guitar(C7, "drop2"));
show("guitar drop3 Cmaj7", ChordVoicings.guitar(Cmaj7, "drop3"));
show("guitar triad3 C", ChordVoicings.guitar(C, "triad3"));
show("guitar shell3 G7", ChordVoicings.guitar({ root:7, intervals:[0,4,7,10] }, "shell3"));
show("guitar shell3 C (-> triads)", ChordVoicings.guitar(C, "shell3"));
show("guitar drop2 C triad", ChordVoicings.guitar(C, "drop2"));
show("guitar drop3 G triad", ChordVoicings.guitar({ root:7, intervals:[0,4,7] }, "drop3"));
show("guitar triad3 C5", ChordVoicings.guitar({ root:0, intervals:[0,7] }, "triad3"));
show("uke drop2 C7", ChordVoicings.guitar(C7, "drop2", { tuning:[67,60,64,69] }));
show("uke drop3 C7", ChordVoicings.guitar(C7, "drop3", { tuning:[67,60,64,69] }));
console.log(JSON.stringify(ChordVoicings.reduce({ root:0, intervals:[0,4,8,10,13,15] })), JSON.stringify(ChordVoicings.reduce({ root:0, intervals:[0,4,7,10,14,17] })));
console.log(ChordVoicings.intervalsFromFormula("1 b3 5 b7 9 #11 13"), JSON.stringify(ChordVoicings.styles("guitar")));
